Knp\Component\Pager\Pagination\AbstractPagination:
    exclusion_policy: ALL
    properties:
        items:
            expose: true
            access_type: public_method
            accessor:
                getter: getItems
            type: array
            serialized_name:
                users
        customParameters:
            expose: true
            xml_key_value_pairs: true
            serialized_name:
                pagination
