CanalTP\NavitiaIoCoreApiBundle\Entity\Key:
    exclusion_policy: ALL
    access_type: property
    xml_root_name: key
    properties:
        id:
            expose: true
        key:
            expose: true
        appName:
            expose: true
