CanalTP\NavitiaIoCoreApiBundle\Entity\Token:
    exclusion_policy: ALL
    access_type: property
    xml_root_name: token
    properties:
        id:
            expose: true
        key:
            expose: true
        appName:
            expose: true
